name: Build QMK Firmware

on:
  push:
    tags:
      - "j2-v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Build Firmware
        run: |
          qmk clean
          qmk compile \
            -e BUILD_DIR=.build \
            -e SKIP_GIT=1 \
            -e TARGET=jamesdonkey_j2_custom-${{ github.ref_name }} \
            -kb jamesdonkey/j2 -km custom

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          # jamesdonkey j2 should use .bin file
          files: |
            .build/*.bin
            .build/*.hex
